### ISSUE TITLE
language mode not used in aishell?

### ISSUE THREAD

**Issue by helloword12345678** [thu-spmi/CAT#10]
thanks for sharing! i do aishell dataset,but i find that language model is not used in the decode process? is i am right?

**Comment by helloword12345678** [comment]
what't the purpose of 'den_lm.fst'?

**Comment by thu-spmi** [comment]
'den_lm.fst' is needed in calculating CRF gradients, which is different from the word-level language model used in decoding.
Please refer to [http://oa.ee.tsinghua.edu.cn/~ouzhijian/pdf/ctc-crf.pdf](the CTC-CRF paper) for details, particularly looking for the introduction of the n-gram denominator LM of labels.
