### ISSUE TITLE
GPU-DEN blank_index is defalut 0?

### ISSUE THREAD

**Issue by TeaPoly** [thu-spmi/CAT#11]
It's not support adjust blank_index to other index. But gpu_ctc support. Is it mean blank index is not important for gpu_den?

**Comment by hyx16** [comment]
Gpu_den is used to calculate the gradients of the denominator graph. Blank_index is 1 by default when creating the denominator graph (considering that <eps> is 0 in WFST) . You can change the blank index when creating the denominator graph (not support now). Gpu_den only does calculation, no matter what the blank index is.

**Comment by TeaPoly** [comment]
> Gpu_den is used to calculate the gradients of the denominator graph. Blank_index is 1 by default when creating the denominator graph (considering that <eps> is 0 in WFST) . You can change the blank index when creating the denominator graph (not support now). Gpu_den only does calculation, no matter what the blank index is.

Thank you for your reply.
