### ISSUE TITLE
I has implement Tensorflow binding, but gradient maye error.

### ISSUE THREAD

**Issue by TeaPoly** [thu-spmi/CAT#12]
I have modifies `warp-ctc` Tensorflow binding and `CAT` pytorch binding, besides I have removed `costs_beta` (maybe useless).
 
```python
def ctc_crf_loss(logits, labels, input_lengths,
                 blank_label=0, lamb=0.1):
  '''Computes the CTC-CRF loss between a sequence of logits and a
  ground truth labeling.

  Args:
      logits: A 3-D Tensor of floats. The dimensions
                   should be (t, n, a), where t is the time index, n
                   is the minibatch index, and a indexes over
                   logits for each symbol in the alphabet.

      labels: An int32 SparseTensor. labels.indices[i, :] == [b, t] means 
              labels.values[i] stores the id for (batch b, time t). 
              labels.values[i] must take on values in [0, num_labels).

      input_lengths: A 1-D Tensor of ints, the number of time steps
                     for each sequence in the minibatch.

      blank_label: int, the label value/index that the CTC
                   calculation should use as the blank label.

      lamb: float, A weight α for CTC Loss. 
                  Combined with the CRF loss to help convergence.

  Returns:
      1-D float Tensor, the cost of each example in the minibatch
      (as negative log probabilities).

  * This class performs the softmax operation internally.

  * The label reserved for the blank symbol should be label 0.

  '''
  # The input of the warp-ctc is modified to be the log-softmax output of the bottom neural network.
  activations = tf.nn.log_softmax(logits) # (t, n, a)
  activations_ = tf.transpose(activations, (1, 0, 2)) # (n, t, a)
  loss, _, _, costs_alpha = _ctc_crf.ctc_crf_loss(
      activations, activations_, labels.indices, labels.values,
      input_lengths, blank_label, lamb) # costs, gradients, grad_net, costs_alpha

  return (costs_alpha - (1 + lamb) * loss)  # (n,)


@ops.RegisterGradient("CtcCrfLoss")
def _CTCLossGrad(op, grad_loss, a, b, c):
  """The derivative provided by CTC-CRF Loss.

  Args:
     op: the CtcCrfLoss op.
     grad_loss: The backprop for cost.

  Returns:
     The CTC-CRF Loss gradient.
  """
  lamb = op.get_attr('lamb')
  grad_ctc = op.outputs[1] # (t, n, a)
  grad_den = tf.transpose(op.outputs[2], (1, 0, 2)) # (t, n, a)
  grad = grad_den - (1 + lamb) * grad_ctc # (t, n, a)
  # average with batch size.
  grad /= tf.cast(_get_dim(grad, 1), dtype=tf.float32) # (t, n, a)

  # Return gradient for inputs and None for
  # activations_, labels_indices, labels_values and sequence_length.
  return [_BroadcastMul(grad_loss, grad), None, None, None, None]
  # return [_BroadcastMul(grad_loss, op.outputs[1]), None, None, None, None]

```

I can provide all the codes if necessary, but my result is error because TER is over 100%.

**Comment by TeaPoly** [comment]
In my option:
`CRF_Loss` = `-(log_prob_ctc-log_prob_den)`+`lamb*(-log_prob_ctc) ` = `log_ prob_den` - `(1+lamb)*log_prob_ctc`, so the  `ctc_crf_base.gpu_ctc`, `ctc_crf_base.gpu_den` output is `log_prob_ctc` and `log_prob_den`, not the mean of loss.
I guess the gradient is `-(grad_den - (1 + lamb) * grad_ctc)`. Please correct me if wrong.

**Comment by hyx16** [comment]
> In my option:
> `CRF_Loss` = `-(log_prob_ctc-log_prob_den)`+`lamb*(-log_prob_ctc) ` = `log_ prob_den` - `(1+lamb)*log_prob_ctc`, so the `ctc_crf_base.gpu_ctc`, `ctc_crf_base.gpu_den` output is `log_prob_ctc` and `log_prob_den`, not the mean of loss.
> I guess the gradient is `-(grad_den - (1 + lamb) * grad_ctc)`. Please correct me if wrong.

I think the gradient is `grad_den - (1 + lamb) * grad_ctc.`

**Comment by TeaPoly** [comment]
> > In my option:
> 
> > `CRF_Loss` = `-(log_prob_ctc-log_prob_den)`+`lamb*(-log_prob_ctc) ` = `log_ prob_den` - `(1+lamb)*log_prob_ctc`, so the `ctc_crf_base.gpu_ctc`, `ctc_crf_base.gpu_den` output is `log_prob_ctc` and `log_prob_den`, not the mean of loss.
> 
> > I guess the gradient is `-(grad_den - (1 + lamb) * grad_ctc)`. Please correct me if wrong.
> 
> 
> 
> I think the gradient is `grad_den - (1 + lamb) * grad_ctc.`
> 
> 

Yes，you are right. I think my fst model was wrong.

**Comment by TeaPoly** [comment]
For AISHELL task. I try to replace `real_loss = (partial_loss - weight)` with Phoneme Error Rate (use CTC greedy search and edit distance to calculate) each epoch for evaluating. Is this a problem?

**Comment by aky15** [comment]
Maybe you can have a try. The learning rate decay procedure is controled by the evaluation loss (in train.py,we call it cv loss) so the final results may differ.

**Comment by aky15** [comment]
> For AISHELL task. I try to replace `real_loss = (partial_loss - weight)` with Phoneme Error Rate (use CTC greedy search and edit distance to calculate) each epoch for evaluating. Is this a problem?

Maybe you can have a try. The learning rate decay procedure is controled by the evaluation loss (in train.py,we call it cv loss) so the final results may differ.

**Comment by TeaPoly** [comment]
> > For AISHELL task. I try to replace `real_loss = (partial_loss - weight)` with Phoneme Error Rate (use CTC greedy search and edit distance to calculate) each epoch for evaluating. Is this a problem?
> 
> Maybe you can have a try. The learning rate decay procedure is controled by the evaluation loss (in train.py,we call it cv loss) so the final results may differ.

I try to use PER and cost, but my expriment still cannot convergence.
I notice egs/wsj/steps/ctc_crf.py#33 and src/ctc_crf/binding_1_0.cpp#L89
https://github.com/thu-spmi/CAT/blob/6e76b4e2b8d1bc2f584c5decaabaf495ad31d9c4/egs/wsj/steps/ctc_crf.py#L33

https://github.com/thu-spmi/CAT/blob/6e76b4e2b8d1bc2f584c5decaabaf495ad31d9c4/src/ctc_crf/binding_1_0.cpp#L89-L90

I think `costs_beta_den` and `costs_beta_ptr` is not useless and I remove those values. Should this value have no effect on the subsequent operations?

**Comment by TeaPoly** [comment]
> > In my option:
> > `CRF_Loss` = `-(log_prob_ctc-log_prob_den)`+`lamb*(-log_prob_ctc) ` = `log_ prob_den` - `(1+lamb)*log_prob_ctc`, so the `ctc_crf_base.gpu_ctc`, `ctc_crf_base.gpu_den` output is `log_prob_ctc` and `log_prob_den`, not the mean of loss.
> > I guess the gradient is `-(grad_den - (1 + lamb) * grad_ctc)`. Please correct me if wrong.
> 
> I think the gradient is `grad_den - (1 + lamb) * grad_ctc.`

I have use egs/aishell run scrpit. And the exp result is all corrected. But my all task is in Tensorflow. So I implement a Tensorflow API for CAT. But I find gpu_ctc part is corrected and gpu_den result is wrong, and gpu_den result is different every time. So I doubt the implement with Tensorflow API memory manager or GPU caculation has error.
I knew some code in GPU_DEN is written by you. So this part of the implementation is very familiar to you. Can you give me some advices.

**Comment by TeaPoly** [comment]
> > In my option:
> > `CRF_Loss` = `-(log_prob_ctc-log_prob_den)`+`lamb*(-log_prob_ctc) ` = `log_ prob_den` - `(1+lamb)*log_prob_ctc`, so the `ctc_crf_base.gpu_ctc`, `ctc_crf_base.gpu_den` output is `log_prob_ctc` and `log_prob_den`, not the mean of loss.
> > I guess the gradient is `-(grad_den - (1 + lamb) * grad_ctc)`. Please correct me if wrong.
> 
> I think the gradient is `grad_den - (1 + lamb) * grad_ctc.`

I have use egs/aishell run scrpit. And the exp result is all corrected. But my all task is in Tensorflow. So I implement a Tensorflow API for CAT. 
But I find gpu_ctc part is corrected and gpu_den result is wrong, and gpu_den result is different every time. So I doubt the implement with Tensorflow API memory manager or GPU caculation has error.
I knew some code in GPU_DEN is written by you. So this part of the implementation is very familiar to you. Can you give me some advices.

**Comment by TeaPoly** [comment]
> > In my option:
> > `CRF_Loss` = `-(log_prob_ctc-log_prob_den)`+`lamb*(-log_prob_ctc) ` = `log_ prob_den` - `(1+lamb)*log_prob_ctc`, so the `ctc_crf_base.gpu_ctc`, `ctc_crf_base.gpu_den` output is `log_prob_ctc` and `log_prob_den`, not the mean of loss.
> > I guess the gradient is `-(grad_den - (1 + lamb) * grad_ctc)`. Please correct me if wrong.
> 
> I think the gradient is `grad_den - (1 + lamb) * grad_ctc.`

I have use egs/aishell run scrpit. And the exp result is all corrected. But my all task is in Tensorflow. So I implement a Tensorflow API for CAT.
But I find gpu_ctc part is corrected and gpu_den result is wrong, and gpu_den result is different every time. So I doubt the implement with Tensorflow API memory manager or GPU caculation has error.
I knew some code in GPU_DEN is written by you. So this part of the implementation is very familiar to you. Can you give me some advices. Repo is here: [CAT-Tensorflow](https://github.com/TeaPoly/CAT-Tensorflow)

**Comment by hyx16** [comment]
Thanks for you attention. I am not familiar with tensorflow binding and I am a little busy recently. You can check whether  `costs_alpha ` equals to  `costs_beta `. I may take a look this weekend if you still do not solve it.

**Comment by TeaPoly** [comment]
> Thanks for you attention. I am not familiar with tensorflow binding and I am a little busy recently. You can check whether `costs_alpha ` equals to `costs_beta `. I may take a look this weekend if you still do not solve it.

I understand. Thank you so much for your suggestion.

**Comment by TeaPoly** [comment]
> costs_beta

So the `costs_beta` is for verify the effectiveness of the algorithm?  I deleted `costs_beta` that I thought it was useless.

**Comment by hyx16** [comment]
> > costs_beta
> 
> So the `costs_beta` is for verify the effectiveness of the algorithm? I deleted `costs_beta` that I thought it was useless.

`costs_beta` should be equal to  `costs_alpha` in theory, so it is actually useless if everything is all
 right。`costs_beta` can be used to to check the correctness of the denominator computation. If the
 difference between `costs_beta` and `costs_alpha` is large, there might be something wrong with the denominator computation.

**Comment by TeaPoly** [comment]
> > > costs_beta
> > 
> > 
> > So the `costs_beta` is for verify the effectiveness of the algorithm? I deleted `costs_beta` that I thought it was useless.
> 
> `costs_beta` should be equal to `costs_alpha` in theory, so it is actually useless if everything is all
> right。`costs_beta` can be used to to check the correctness of the denominator computation. If the
> difference between `costs_beta` and `costs_alpha` is large, there might be something wrong with the denominator computation.

I found that my expriment is actually divides the batch into several equal parts to every GPU for parallel training. 
For example,  setting `batch_size=128` and GPUs set is `[0,1,2,3]`, each GPU wiil get 32 samples. However, the GPU_DEN calculation device is always zero (`int device = 0;`). This may causes the results to be biased. Is that right?

**Comment by TeaPoly** [comment]
In my task, I allocate a mini-batch equally according to the number of GPUs, and then do parallel calculations. For example, `batch_size=32` and GPU setting is `[0,1,2,3]`, each GPU will get 8 samples. Is this not very compatible with `GPU_DEN`.

**Comment by hyx16** [comment]
I am not familiar with tensorflow's multi-GPU training strategy. GPU_DEN can do multi-GPU calculation using pytorch DataParallel (although the implementation is a little ugly). Are the results right if you use a single GPU?

**Comment by TeaPoly** [comment]
I have a very strange problem：

when I use only use CTC loss and gradient in CTC-CRF, it can converge to a good result :
```python3
def ctc_crf_loss(logits, labels, input_lengths,
                 blank_label=0, lamb=0.1):
  # The input of the warp-ctc is modified to be the log-softmax output of the bottom neural network.
  activations = tf.nn.log_softmax(logits) # (t, n, a)
  activations_ = tf.transpose(activations, (1, 0, 2)) # (n, t, a)
  log_prob_ctc, _, _, log_prob_den, _ = _ctc_crf.ctc_crf_loss(
      activations, activations_, labels.indices, labels.values,
      input_lengths, blank_label, lamb) # costs, gradients, grad_net, costs_alpha, cost_beta
  return -log_prob_ctc

@ops.RegisterGradient("CtcCrfLoss")
def _CTCLossGrad(op, grad_loss, a, b, c):
  # Return gradient for inputs and None for
  # activations_, labels_indices, labels_values and sequence_length.
 return [_BroadcastMul(grad_loss, op.outputs[1]), None, None, None, None]
```

but when I use CTC-CRF loss, using the same GPU_CTC and GPU_DEN code (lamb==0.01 for AISHELL), it cannot converge, cost with corresponding path weights is always bigger than 1500, and it's going to go up to tens of thousands:

```python3
def ctc_crf_loss(logits, labels, input_lengths,
                 blank_label=0, lamb=0.1):
  # The input of the warp-ctc is modified to be the log-softmax output of the bottom neural network.
  activations = tf.nn.log_softmax(logits) # (t, n, a)
  activations_ = tf.transpose(activations, (1, 0, 2)) # (n, t, a)
  log_prob_ctc, _, _, log_prob_den, _ = _ctc_crf.ctc_crf_loss(
      activations, activations_, labels.indices, labels.values,
      input_lengths, blank_label, lamb) # costs, gradients, grad_net, costs_alpha, cost_beta
  return (log_prob_den - (1 + lamb) * log_prob_ctc)

@ops.RegisterGradient("CtcCrfLoss")
def _CTCLossGrad(op, grad_loss, a, b, c):
  lamb = op.get_attr('lamb')
  grad_ctc = op.outputs[1] # (t, n, a)
  grad_den = tf.transpose(op.outputs[2], (1, 0, 2)) # (t, n, a)
  grad = grad_den - (1+lamb)*grad_ctc # (t, n, a)
  # average with batch size.
  grad /= tf.cast(_get_dim(grad, 1), dtype=tf.float32) # (t, n, a)

  # Return gradient for inputs and None for
  # activations_, labels_indices, labels_values and sequence_length.
  return [_BroadcastMul(grad_loss, grad), None, None, None, None]
```

(t, n, a), where t is the time index, n is the minibatch index, and a indexes over logits for each symbol in the alphabet.

**Comment by TeaPoly** [comment]
> I am not familiar with tensorflow's multi-GPU training strategy. GPU_DEN can do multi-GPU calculation using pytorch DataParallel (although the implementation is a little ugly). Are the results right if you use a single GPU?

Thanks for your reply. Results is not right. I think my implement @ops.RegisterGradient("CtcCrfLoss") has error. Need to learn more about Tensorflow gradient function.

**Comment by TeaPoly** [comment]
> I am not familiar with tensorflow's multi-GPU training strategy. GPU_DEN can do multi-GPU calculation using pytorch DataParallel (although the implementation is a little ugly). Are the results right if you use a single GPU?

I find it strange that it is possible to converge to a desired result when I use only CTC loss and gradient part, like this:
```python3 
def ctc_crf_loss(logits, labels, input_lengths,
                 blank_label=0, lamb=0.1):
  # The input of the warp-ctc is modified to be the log-softmax output of the bottom neural network.
  activations = tf.nn.log_softmax(logits) # (t, n, a)
  activations_ = tf.transpose(activations, (1, 0, 2)) # (n, t, a)
  loss, _, _, costs_alpha = _ctc_crf.ctc_crf_loss(
      activations, activations_, labels.indices, labels.values,
      input_lengths, blank_label, lamb) # costs, gradients, grad_net, costs_alpha
  return -loss

@ops.RegisterGradient("CtcCrfLoss")
def _CTCLossGrad(op, grad_loss, a, b, c):
  # Return gradient for inputs and None for
  # activations_, labels_indices, labels_values and sequence_length.
  return [_BroadcastMul(grad_loss, op.outputs[1]), None, None, None, None]

```

But when I using CTC-CAT loss like that, the result is bad. And cost is over ten thounds.

```python3
def ctc_crf_loss(logits, labels, input_lengths,
                 blank_label=0, lamb=0.1):
  # The input of the warp-ctc is modified to be the log-softmax output of the bottom neural network.
  activations = tf.nn.log_softmax(logits) # (t, n, a)
  activations_ = tf.transpose(activations, (1, 0, 2)) # (n, t, a)
  loss, _, _, costs_alpha = _ctc_crf.ctc_crf_loss(
      activations, activations_, labels.indices, labels.values,
      input_lengths, blank_label, lamb) # costs, gradients, grad_net, costs_alpha

  return (costs_alpha - (1 + lamb) * loss)  # (n,)


@ops.RegisterGradient("CtcCrfLoss")
def _CTCLossGrad(op, grad_loss, a, b, c):
  lamb = op.get_attr('lamb')
  grad_ctc = op.outputs[1] # (t, n, a)
  grad_den = tf.transpose(op.outputs[2], (1, 0, 2)) # (t, n, a)
  grad = grad_den - (1 + lamb) * grad_ctc # (t, n, a)
  # average with batch size.
  grad /= tf.cast(_get_dim(grad, 1), dtype=tf.float32) # (t, n, a)

  # Return gradient for inputs and None for
  # activations_, labels_indices, labels_values and sequence_length.
  return [_BroadcastMul(grad_loss, grad), None, None, None, None]
```

**Comment by TeaPoly** [comment]
> I am not familiar with tensorflow's multi-GPU training strategy. GPU_DEN can do multi-GPU calculation using pytorch DataParallel (although the implementation is a little ugly). Are the results right if you use a single GPU?

Thanks for your reply, dose GPU_DEN has a CPU vesion? I think tensorflow is hard to specifies that the sensor allocates memory on the GPU. So the result is not expected.

**Comment by hyx16** [comment]
GPU_DEN only has a gpu version. Calculating the gradient of the denominator graph on CPU is very slow.

**Comment by TeaPoly** [comment]
> > > costs_beta
> > 
> > 
> > So the `costs_beta` is for verify the effectiveness of the algorithm? I deleted `costs_beta` that I thought it was useless.
> 
> `costs_beta` should be equal to `costs_alpha` in theory, so it is actually useless if everything is all
> right。`costs_beta` can be used to to check the correctness of the denominator computation. If the
> difference between `costs_beta` and `costs_alpha` is large, there might be something wrong with the denominator computation.

Is it possibility caused by GPU asynchronous call If `cost_alph` not equal to `cost_beta`?

**Comment by hyx16** [comment]
> Is it possibility caused by GPU asynchronous call If `cost_alph` not equal to `cost_beta`?

Maybe. But I think in the code I have synchronized the GPU threads when necessary.

**Comment by TeaPoly** [comment]
> > Is it possibility caused by GPU asynchronous call If `cost_alph` not equal to `cost_beta`?
> 
> Maybe. But I think in the code I have synchronized the GPU threads when necessary.

Thank you for your help. 
The previous problem is that my test logits dimension is less than 218 which AISHELL phoneme set is 217+1(blank). Tensorlow binding result is consistent with the results of PyTorch binding now.
I observed that the loss value of my experiment dropped from 100 to 30, but after several hundred steps it rose to several thousand. I will check the other implement detail. If you have similar problems, please tell to me. My acoustic framework is 2xConv2d+2xBiLSTM(320) and every layer with Batchnorm, the result is normal when I only use the ctc part loss and gradient in CAT toolkit.
