### ISSUE TITLE
Issue in compiling Kaldi patch

### ISSUE THREAD

**Issue by omprakashsonie** [thu-spmi/CAT#13]
Copying patch in bin directory and compiling is giving error as it is dependent on other files from directories which are one level above

(base):~/kaldi/src/bin$ gcc -o latgen-faster latgen-faster.cc
latgen-faster.cc:23:31: fatal error: base/kaldi-common.h: No such file or directory

Can you pls suggest the steps to resolve it?

**Comment by aky15** [comment]
Yes, it is dependent on other files. My suggestion is 
copy src/kaldi-patch/latgen-faster.cc to kaldi src/bin，add latgen-faster to the Makefile, and re-compile kaldi.

**Comment by alex-ht** [comment]
Try this! 
https://github.com/alex-ht/CAT/blob/8d5e6b89dd0f088ced0f5c1061efd97c17c4741f/docker/Dockerfile#L9-L13

**Comment by omprakashsonie** [comment]
For now I have recompiled Kaldi. 
Thank you Alex.
