### ISSUE TITLE
Issue in make OPENFST=/path/to/your/openfst

### ISSUE THREAD

**Issue by omprakashsonie** [thu-spmi/CAT#14]
I am using pytorch 1.5 and using python setup_1_0.py install in the ctc_crf/Makefile.

/home/anaconda3/envs/torch_w2l/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/expanding_array.h:23:7: note:   in call to ‘torch::ExpandingArray<2ul, double>& torch::ExpandingArray<2ul, double>::operator=(const torch::ExpandingArray<2ul, double>&)’
 class ExpandingArray {
       ^
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/anaconda3/envs/torch_w2l/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1395, in _run_ninja_build
    subprocess.run(
  File "/home/anaconda3/envs/torch_w2l/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
 
During handling of the above exception, another exception occurred::
:
    _write_ninja_file_and_compile_objects(
  File "/home/anaconda3/envs/torch_w2l/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1135, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/anaconda3/envs/torch_w2l/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
Makefile:22: recipe for target 'CTCCRF' failed
make: *** [CTCCRF] Error 1

Can you pls suggest next steps?

**Comment by aky15** [comment]
This may have something yo do with the pytorch version.
[similar issue](https://github.com/nv-tlabs/GSCNN/issues/15)

**Comment by omprakashsonie** [comment]
Hi,
I am getting following error now:

-- Build files have been written to:
/home/omprakash.s/CAT/src/ctc_crf/gpu_den/build

cd gpu_den/build && make

make[1]: Entering directory
'/home/omprakash.s/CAT/src/ctc_crf/gpu_den/build'

make[2]: Entering directory
'/home/omprakash.s/CAT/src/ctc_crf/gpu_den/build'

make[3]: Entering directory
'/home/omprakash.s/CAT/src/ctc_crf/gpu_den/build'

*Scanning dependencies of target fst_read*

make[3]: Leaving directory '/home/omprakash.s/CAT/src/ctc_crf/gpu_den/build'

make[3]: Entering directory
'/home/omprakash.s/CAT/src/ctc_crf/gpu_den/build'

[ 25%] Building CXX object CMakeFiles/fst_read.dir/fst_read.cc.o

*/home/omprakash.s/CAT/src/ctc_crf/gpu_den/fst_read.cc:5:24:* *fatal error:
*fst/fstlib.h: No such file or directory

compilation terminated.

CMakeFiles/fst_read.dir/build.make:62: recipe for target
'CMakeFiles/fst_read.dir/fst_read.cc.o' failed

make[3]: *** [CMakeFiles/fst_read.dir/fst_read.cc.o] Error 1

make[3]: Leaving directory '/home/omprakash.s/CAT/src/ctc_crf/gpu_den/build'

CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/fst_read.dir/all'
failed

make[2]: *** [CMakeFiles/fst_read.dir/all] Error 2

make[2]: Leaving directory '/home/omprakash.s/CAT/src/ctc_crf/gpu_den/build'

Makefile:83: recipe for target 'all' failed

make[1]: *** [all] Error 2

make[1]: Leaving directory '/home/omprakash.s/CAT/src/ctc_crf/gpu_den/build'

Makefile:14: recipe for target 'GPUDEN' failed

make: *** [GPUDEN] Error 2

**Comment by aky15** [comment]
Make sure to have openfst installed and set the path correctly.

**Comment by omprakashsonie** [comment]
Thanks a lot for your prompt response.
Will try it out.

**Comment by wenjie-p** [comment]
Hi I also encountered this issue recently. Here is my solution in Step3: Install CTC-CRF module
```shell
make OPENFST=<path to openfst> # note the key point is that this should be an ABSOLUTE PATH instead of relative path
```
I think it would be better if specify this explicitly in the file `installing-cat-tutorial.md`, right?
