### ISSUE TITLE
issues python install setup_1_0.py

### ISSUE THREAD

**Issue by FzuGsr** [thu-spmi/CAT#17]
Hi, my env :
torch 1.5.0 
 conda  gcc version is 5.2.0 (GCC)
python:3.6.5

when i run python install setup_1_0.py , get errors
`No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
running install
running bdist_egg
running egg_info
writing ctc_crf_base.egg-info/PKG-INFO
writing dependency_links to ctc_crf_base.egg-info/dependency_links.txt
writing top-level names to ctc_crf_base.egg-info/top_level.txt
reading manifest file 'ctc_crf_base.egg-info/SOURCES.txt'
writing manifest file 'ctc_crf_base.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'ctc_crf_base' extension
gcc -pthread -B /home/sean/anaconda3/envs/p36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sean/anaconda3/envs/p36/lib/python3.6/site-packages/torch/include -I/home/sean/anaconda3/envs/p36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/sean/anaconda3/envs/p36/lib/python3.6/site-packages/torch/include/TH -I/home/sean/anaconda3/envs/p36/lib/python3.6/site-packages/torch/include/THC -I/home/sean/anaconda3/envs/p36/include/python3.6m -c binding_1_0.cpp -o build/temp.linux-x86_64-3.6/binding_1_0.o -std=c++14 -fPIC -I/usr/local/cuda/include -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ctc_crf_base -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
creating build/lib.linux-x86_64-3.6
g++ -pthread -shared -B /home/sean/anaconda3/envs/p36/compiler_compat -L/home/sean/anaconda3/envs/p36/lib -Wl,-rpath=/home/sean/anaconda3/envs/p36/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/binding_1_0.o -L/data00/home/sean/02_workspace/00_github_code/CAT/src/ctc_crf/gpu_ctc/build -L/data00/home/sean/02_workspace/00_github_code/CAT/src/ctc_crf/gpu_den/build -L/home/sean/anaconda3/envs/p36/lib/python3.6/site-packages/torch/lib -lfst_den -lwarpctc -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.6/ctc_crf_base.cpython-36m-x86_64-linux-gnu.so -Wl,-rpath,/data00/home/sean/02_workspace/00_github_code/CAT/src/ctc_crf/gpu_ctc/build -Wl,-rpath,/data00/home/sean/02_workspace/00_github_code/CAT/src/ctc_crf/gpu_den/build
/home/sean/anaconda3/envs/p36/compiler_compat/ld: cannot find -lm
/home/sean/anaconda3/envs/p36/compiler_compat/ld: cannot find -lpthread
/home/sean/anaconda3/envs/p36/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
/home/sean/anaconda3/envs/p36/lib/python3.6/distutils/extension.py:131: UserWarning: Unknown Extension options: 'headers', 'with_cuda'
  warnings.warn(msg)
/home/sean/anaconda3/envs/p36/lib/python3.6/site-packages/torch/utils/cpp_extension.py:304: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
error: command 'g++' failed with exit status 1 `

Can you pls suggest the steps to resolve it? Thanks

**Comment by aky15** [comment]
Have you installed CUDA and set the cuda path in setup_1_0.py accordingly?

**Comment by FzuGsr** [comment]
> Have you installed CUDA and set the cuda path in setup_1_0.py accordingly?

Thank you for your reply. I installed CUDA Version 9.0.176 and  run 
`CUDA_HOME='/usr/local/cuda' python setup_1_0.py install`
get the same error

**Comment by FzuGsr** [comment]
> Have you installed CUDA and set the cuda path in setup_1_0.py accordingly?

Thank you for your reply. I installed CUDA Version 9.0.176 and run
CUDA_HOME='/usr/local/cuda' python setup_1_0.py install
got the same error

**Comment by aky15** [comment]
There may be several possible reasons:
1. The version of cuda in /usr/local/cuda is different from the version you have been using (use nvcc -- version to check it.)
2. The cuda version is too old for the latest pytorch. Can your torch work with CUDA supported?
3. As the log file suggests, you may need ninja as the BuildExtension backend.

**Comment by FzuGsr** [comment]
> There may be several possible reasons:
> 
> 1. The version of cuda in /usr/local/cuda is different from the version you have been using (use nvcc -- version to check it.)
> 2. The cuda version is too old for the latest pytorch. Can your torch work with CUDA supported?
> 3. As the log file suggests, you may need ninja as the BuildExtension backend.

Thank you. I solved it with  pytorch version 1.2
