### ISSUE TITLE
python steps/train.py error

### ISSUE THREAD

**Issue by FzuGsr** [thu-spmi/CAT#18]
Hi, my env :
torch 1.2.0
python:3.6.5

When I run  egs/libri/run.sh 
 `python steps/train.py --output_unit=72 --lamb=0.01 --data_path=$dir` got error:
`    from batchnorm_utils import pytorch as batch_norm
ModuleNotFoundError: No module named 'batchnorm_utils'`

How can i solve it ? Look forward to your reply~ 
Thank you

**Comment by aky15** [comment]
You will need to compile batchnorm_src before using batchnorm_utils. See src/batchnorm_src for details. 
However, for torch 1.* , batchnorm_src is not supported currently  #15.  You can simply comment out this line and use models without batchnorm ( (B)LSTM、VGG(B)LSTM) successfully.

**Comment by FzuGsr** [comment]
> You will need to compile batchnorm_src before using batchnorm_utils. See src/batchnorm_src for details.
> However, for torch 1.* , batchnorm_src is not supported currently #15. You can simply comment out this line and use models without batchnorm ( (B)LSTM、VGG(B)LSTM) successfully.

Thank you ! I will try it later

**Comment by FzuGsr** [comment]
Hi, I run the script libri/ run.sh , using the default parameters, except for batchsize = 64 and training data of 10W.After 4 epoch the loss did not decrease but increased. Is it normal ? Or is there a problem ?

`CUDA_VISIBLE_DEVICES=0,1  python steps/train.py --output_unit=72 --lamb=0.01 --data_path=$dir --batch_size=64`

 loss:
```
training epoch: 1, step: 0 
time: 22962690.88620005, tr_real_loss: 362.5290832519531, lr: 0.001 
training epoch: 1, step: 1 
time: 2.3200497291982174, tr_real_loss: 346.19873046875, lr: 0.001 
... 
cv_real_loss: 1824.0799560546875 
mean_cv_loss: 2086.6042042125355 
training epoch: 2, step: 0 
time: 326.82309682294726, tr_real_loss: 2080.9296875, lr: 0.001 
... 
cv_real_loss: 2053.24267578125 
mean_cv_loss: 2354.7900468306107 
training epoch: 3, step: 0 
time: 325.49561636149883, tr_real_loss: 2357.21923828125, lr: 0.001 
...
cv_real_loss: 2051.596923828125
mean_cv_loss: 2342.086932927912
training epoch: 4, step: 0
time: 325.2704566754401, tr_real_loss: 2315.0703125, lr: 0.001
```
 Look forward to your reply~
Thank you

**Comment by aky15** [comment]
when the batchsize is small , the training may be more unstable. Try to set the lambda larger (e.g. 0.1) to  help the convergence.

**Comment by FzuGsr** [comment]
> when the batchsize is small , the training may be more unstable. Try to set the lambda larger (e.g. 0.1) to help the convergence.

Thank you for your reply.
Still can't converge. I set the lambda 0.1 and batch 90 and  get loss 2w+ .
I try aishell and get cer  7.92. It is there any problem to run libri/run.sh ?

Look forward to your reply~
Thank you

**Comment by aky15** [comment]
Hi, @FzuGsr , issue #22 may help.
