### ISSUE TITLE
 error: identifier "__shfl_up_sync" is undefined

### ISSUE THREAD

**Issue by donstang** [thu-spmi/CAT#34]
make ctc_crf  use cuda 10.0

**Comment by aky15** [comment]
__shfl_up_sync should work fine with CUDA 10.0 [https://docs.nvidia.com/cuda/archive/10.0/cuda-c-programming-guide/index.html](https://docs.nvidia.com/cuda/archive/10.0/cuda-c-programming-guide/index.html). 
Perhaps you should check CUDA you used. Is your PyTorch compiled with CUDA10.0 support?

**Comment by donstang** [comment]
pytorch compile sucess with cuda 10.0

baidu warp_ctc is also compiled sucess

**Comment by aky15** [comment]
We have updated CMakeLists.txt to be consistent with warp-ctc. #33

**Comment by donstang** [comment]
update the code, complie sucess. Thanks
