### ISSUE TITLE
关于音位特征功能支持

### ISSUE THREAD

**Issue by lhppom** [thu-spmi/CAT#52]
您好，论文《MULTILINGUAL AND CROSSLINGUAL SPEECH RECOGNITION USING PHONOLOGICAL-VECTOR BASED PHONE EMBEDDINGS》在跨语言语音识别中是个有意思的工作，其中提到相关工作会在本工具包中实现，想问下目前的支持计划是怎么样的呢？谢谢～

**Comment by maxwellzh** [comment]
您好，感谢您对我们工作的关注。该文章对应工作的代码我们已经基本完成整理，目前处于code review阶段，应该会在一周内就能merge到master branch。

**Comment by maxwellzh** [comment]
@lhppom 你好，相关的代码已经整理合并到master分支，可以参考https://github.com/thu-spmi/CAT/blob/master/egs/commonvoice/run_mc.sh 运行实验
