### ISSUE TITLE
gcc-9如何安装？

### ISSUE THREAD

**Issue by Sar-Dar** [thu-spmi/CAT#55]
Ubuntu 20.04.3     gcc version 9.4.0   如何安装？

**Comment by maxwellzh** [comment]
您好，
目前`ctc_crf` loss模块的编译暂时不支持gcc 9，您可以尝试使用gcc 6/7，在`src/ctc_crf/`目录下，执行
```
CC=gcc-6 CXX=g++-6 make
# 或者使用gcc 7
CC=gcc-7 CXX=g++-7 make
```

**Comment by Sar-Dar** [comment]
gcc 7 环境下安装成功    谢谢！
