### ISSUE TITLE
支持cuda 11.1吗？

### ISSUE THREAD

**Issue by Sundy1219** [thu-spmi/CAT#57]
目前，我的配置改成了Geforce RTX 3080,需要11.1的cuda版本，pytorch=1.8.1,请问怎么支持?

**Comment by maxwellzh** [comment]
支持的，只要确保你的环境变量下cuda版本和pytorch的cuda版本一致即可直接安装，可以通过运行

```
whereis cuda
# 输出类似：cuda: /usr/local/cuda
# 根据输出信息运行
/usr/local/cuda/bin/nvcc --version
```
查看当前运行环境下的cuda版本，如果默认的cuda版本不一致（例如是10.2或者11.3）可以自行安装cuda 11.1版本到指定的目录，然后添加到PATH下
```
export PATH=/usr/local/cuda-11.1/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-11.1/lib64\
                         ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```
这样在编译时就会使用指定的cuda

**Comment by Sundy1219** [comment]
ctc_crf/gpu_ctc/CMakeLists里面需要改动的？如果我要装11.1，这里会找不到吧？加一个11.1的选项？
![Uploading cuda.jpg…]()

**Comment by maxwellzh** [comment]
不需要，在cuda 11.1-11.3都实际测试使用过

**Comment by Sundy1219** [comment]
好的，太棒了
