### ISSUE TITLE
SIGSEGV segmentation fault

### ISSUE THREAD

**Issue by FL990** [thu-spmi/CAT#58]
Hi, thank you for your work.

I import your code as ctc-crf package into my DL model.
In my training code, I calculate loss with
`loss = CRFLoss(logits, labels, inputLenBatch, input_lengths)`

I run my training code with **faulthandler**, and I received **_segmentation fault_**.
![segfault(1)](https://user-images.githubusercontent.com/47623435/167468227-b018fbc4-336f-4925-a8aa-f8770114d927.png)
`train_crf.py` import `general_crf.py`, and `general_crf.py` import CRFLoss from `__init__.py`.

in `__init__` line86 is the **blank_label index**
![segfault(2)](https://user-images.githubusercontent.com/47623435/167468269-914b8d9e-32ba-4a0b-8e52-3fc35c98d017.png)
By the way, due to different data & dataloader, my batchsize is in logits.size(1), I only changed this part.

As you can see, the last input of gpu_ctc is blank_label index.
![segfault(4)](https://user-images.githubusercontent.com/47623435/167472151-13f9c933-7e99-49d7-a18a-31c69b2e3c24.png)

However when I run training code with gdb, I received segmentation fault too, but occurs on different line.
![segfault(3)](https://user-images.githubusercontent.com/47623435/167470108-5f980c0b-a319-4a60-bbb7-42f0454d5936.png)
I guess it's because of `options` in `get_workspace_size`.
So the problem is still on **blank_label index**.

I don't understand why blank_label index causes this fault.
wandering how to solve it, could you help?

**Comment by maxwellzh** [comment]
What's the definition of the `CRFLoss`?

**Comment by FL990** [comment]
The definition of the CRFLoss is in my `train_crf.py`.
Original `train_crf.py`, I use
```
loss_function = nn.CTCLoss(blank=0, zero_infinity=False)
```

I changed this line into
```
loss_function = CRFLoss()
```
(CRFLoss() function is in ctc_crf/ctc_crf/__init__.py)



And then use it for **train** function (**train** is from my `general_crf.py`)
```
trainingLoss, trainingCER, trainingWER = train(model, trainLoader, optimizer, loss_function, device, trainParams)
```

In my `general_crf.py`, in the `def train`, I calaulate loss with
```
loss = CRFLoss(logits, labels, inputLenBatch, input_lengths)
loss.backward()
```
感谢你的回覆!
整个流程是这样的
我把`train_crf.py`中的 nn.CTCLoss 改成你们的 CRFLoss()
在`train_crf.py`中使用到 ctc_crf/ctc_crf/init.py 的 class CTC_CRF_LOSS(Module)  (引用后命名CRFLoss())
并引用`general_crf.py`中的 train 函式做训练
在 train 函式中使用
```
loss = CRFLoss(logits, labels, inputLenBatch, input_lengths)
```
做损失的计算

**Comment by maxwellzh** [comment]
pytorch提供的`nn.CTCLoss`和我们的`CTC_CRF_LOSS`的使用方法是不同的
1. `nn.CTCLoss` 要求输入是`(T, N, V)` （分别表示最大帧长度、batch大小，输出维度）
2. `CTC_CRF_LOSS`要求输入是`(N, T, V)`
此外`CTC_CRF_LOSS`还需要初始化分母图，具体使用例子可以参考
#60

**Comment by FL990** [comment]
我有注意到张量的内容维度不同
我是用transpose转置
```
logits = torch.transpose(logits, 0, 1).contiguous()
```
这应该能够解决？
我会去下载 LM den_lm.txt 试你的测试程式
並会再告诉你结果
谢谢你的帮助!

**Comment by maxwellzh** [comment]
> 这应该能够解决？

是的，通过转置可以解决这个tensor维度不同的问题。

请问在你的代码中是否初始化了den_lm呢？

**Comment by FL990** [comment]
我参考了你的教学安装ctc_crf 模块
https://github.com/thu-spmi/CAT/blob/master/install.md#cat
但并没有对den_lm做改动

**Comment by maxwellzh** [comment]
> 但并没有对den_lm做改动

1. 在示例 #60 中使用我提供的`den_lm.txt`文件是没问题的；
2. 但在实际使用中，需要在你的训练集文本上训练一个对应的den_lm

**Comment by FL990** [comment]
训练den_lm的方法是参考这里吗
https://github.com/thu-spmi/CAT/blob/master/toolkitworkflow.md#denominator-lm-preparation

另外，它是使用lexicon.txt，也就是groundtruth的txt档案训练语言模型，我的理解对吗?

**Comment by maxwellzh** [comment]
>训练den_lm的方法是参考这里吗

是的

> 它是使用lexicon.txt，也就是groundtruth的txt档案训练语言模型

一般来说，lexicon.txt的作用是将词转换为对应的phone，例如（以汉字拼音为例）：你好 -> n i2 h ao3
如果是按照汉字为单元建模，lexicon.txt的内容就是类似：你好 -> 你 好

将文本转换为对应的建模单元后，还需要将建模单元映射到对应的编号（也就是上面提到的`(N, T, V)` tensor中，V维度的序号）

den_lm的训练语料是训练集ground-truth的txt转换为token编号后的内容，实际的例子可以参考
https://github.com/thu-spmi/CAT/blob/15ed6f22b31f76f77c1349d32b824b92b1667629/egs/wsj/run.sh#L76-L81

**Comment by FL990** [comment]
看来我似乎把lexicon.txt和groundtruth的txt档案搞混了
谢谢你的解释!
我打算参照你节录的这段训练lm
可能要点时间，有后续再回报给你!

**Comment by FL990** [comment]
由于dataset的不同，而且我没有wsj的存取权
我只能详细阅读你的workflow，并尝试对我的dataset做一样的处理以生成den_lm.fst。
我注意到你训练的是**phone**-based language model，如果我想生成**character**-based language model应该怎么做，替换掉`chain-est-phone-lm`吗？

**Comment by maxwellzh** [comment]
无论是phone/char-based，都可以使用`chain-est-phone-lm`，它的作用只是训练一个n-gram的语言模型

**Comment by FL990** [comment]
有几个问题请教
1. text_number和unique_text_number是单一的.txt档案对吗？
2. text_number.txt是是依单字做分行，亦或是或句子？
3. units.txt是纪录character跟对应的label，你在 ctc_token_fst_corrected.py使用的token.txt是units.txt加上<eps>和<blk>和消歧符号disambiguation symbols，请问这消歧符号是什么意思？
https://github.com/thu-spmi/CAT/blob/15ed6f22b31f76f77c1349d32b824b92b1667629/scripts/ctc-crf/ctc_compile_dict_token.sh#L57-L60

我使用的数据集是把每个句子的groundtruth独立存档，整理了一下，我要做的应该是
（1）把groundtruth的文字转为label，逐行存入text_number.txt
（2）使用chain-est-phone-lm，他会将text_number.txt排序并去掉完全相同的行，存成unique_text_number.txt，然后训练lm，生成phone_lm.fst
（3）使用ctc_token_fst_corrected.py，输入token.txt，生成T.fst
（4）结合T.fst和phone_lm.fst，产生den_lm.fst
请问我的理解是对的吗？

**Comment by maxwellzh** [comment]
1. > text_number和unique_text_number是单一的.txt档案对吗？
    
   是的，如果你的文本是按句子保存的，你可以通过`cat a.txt b.txt c.txt > text`来合并它们

2. > text_number.txt是是依单字做分行，亦或是或句子？

   `text_number`的每一行结构为
   ```
   <utterance id> <token 0> <token 1> <token 2> ...
   ```
   `<token i>` 取决于你的建模单元，例如：phone为单元时，每个token代表一个音素（对应的id）；字为建模单元时，每个token为一个character（对应的id）

3. disambiguation symbols是为了构建解码图(TLG)需要的，在构建分母图den_lm时不起作用，所以如果你只是构建分母图，可以忽略他们；具体细节可以参考kaldi的文档 https://kaldi-asr.org/doc/graph.html


> 我要做的应该是 ...

基本上是这样，这里我提供一个示例（展示了 #60 中的den_lm构建过程）。
`ground-truth.txt`：训练集文本，只有一句话`a cat sat`，为了简单考虑，我使用英文char建模，并忽略了空格
```
utterance_0 a c a t s a t
```

`units.txt`：标签文本到ID的映射，注意这里0是没有标签映射的，我将其保留为CTC的`blank_label`
```
a 1
c 2
s 3
t 4
```
`text_number.txt`：根据`units.txt`将`ground-truth.txt`翻译得到
```
utterance_0 1 2 1 4 3 1 4
```
然后你可以根据你的需要是否过滤内容重复的行得到`unique_text_number.txt`，这里只有一句话，所以就不需要了。

`tokens.txt`: 根据`units.txt`生成，添加了前面保留的`blank_label`（表示为`<blk>`），还额外添加了一个特殊符号`<eps>`用于表示没有输入，对应的label的ID都+1
```
<eps> 0
<blk> 1
a 2
c 3
s 4
t 5
```
以上就完成了数据的处理，接下来的步骤是

1. LM的训练：使用`chain-est-phone-lm`工具，生成`phone_lm.fst`。默认生成的语言模型是4阶的
2. 使用`ctc-crf/ctc_token_fst_corrected.py` 和`tokens.txt`生成`T.fst`。要注意的是，在`T.fst`中，同一个ID在输入和输出中对应的标签文本是不同的，例如：2在输入中表示`a`，在输出中表示`c`。可以参考 #46 的讨论
3. 将T.fst和phone_lm.fst合并，得到den_lm.fst

**Comment by FL990** [comment]
你的举例解释的很清楚
有些细节想跟你确认，<blk>和CTCLoss的blank label是一样的吗？
另外，论文中提到`<eps>`是“no consuming” (no output)，你也说是没有输入的意思，是代表句子中单字间的空格吗？
例如`a cat sat`是不是
```
utterance_0 a <eps> c a t <eps> s a t
```
转换后变
```
utterance_0 2 0 3 2 5 0 4 2 5
```
然后上面那行是text_number.txt实际内容，这样子对吗？

**Comment by maxwellzh** [comment]
1. blank_label的含义和CTC是一致的；
2. `<eps>`的作用，我没有解释清楚，可以参考fig.3 & fig.4 https://arxiv.org/pdf/1507.08240.pdf
   > The “\<eps\>” symbol means no inputs are consumed or no outputs are emitted.

   `<eps>`不表示任何有意义的token。
   在上面的例子中，出于简单考虑，我直接将原始句子中的空格忽略了，如果要引入空格，`tokens.txt`会变成
   ```
   <eps> 0
   <blk> 1
   a 2
   c 3
   s 4
   t 5
   <space> 6
   ```
   引入`<eps>`只作用在构建`T.fst`上，不会改变`text_number.txt`

**Comment by FL990** [comment]
看过EESEN论文后我还是不太了解`<eps>`的用处
如果`<eps>`不表示任何有意义的token，也不是为了输入输出的对齐(已有`<blk>`)，如何对生成T.fst有帮助?
但实务上我知道该怎么做了，建立text_number.txt不须考虑`<eps>`，但在token.txt需要考虑对吧

**Comment by maxwellzh** [comment]
> 另外，如果我使用你们的CTCLoss，也是需要初始化den_lm.fst对吗?

只使用CTCLoss的话是不需要构建/初始化分母图的，使用上和`torch.nn.CTCLoss`基本一致（参数顺序、维度可能不同）

**Comment by FL990** [comment]
感谢解惑!
刚好程式运行遇到了一个似乎与n_lm无关的问题，将CRFLoss换成CTCLoss做测试（除去den_lm的影响，看是哪里报错）
终端报错如下
```
Traceback (most recent call last):                                         
  File "train_crf.py", line 169, in <module>
    main()
  File "train_crf.py", line 111, in main
    trainingLoss, trainingCER, trainingWER = train(model, trainLoader, optimizer, loss_function, device, trainParams)
  File "/nfs/Workspace/deep_avsr/video_only/utils/general_crf.py", line 43, in train
    ctx = ctc_crf.CRFContext(den_lm, gpus=0)
  File "/opt/conda/lib/python3.6/site-packages/ctc_crf-0.1.0-py3.6-linux-x86_64.egg/ctc_crf/__init__.py", line 143, in __init__
    f"Denominator LM model location is invalid: {den_lm}.")
RuntimeError: Denominator LM model location is invalid: den_lm.txt.
Exception ignored in: <bound method CRFContext.__del__ of <ctc_crf.CRFContext object at 0x7f56d78c9d30>>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/ctc_crf-0.1.0-py3.6-linux-x86_64.egg/ctc_crf/__init__.py", line 156, in __del__
    core.release_env(self._gpus)
AttributeError: 'CRFContext' object has no attribute '_gpus'
```
我的__init__.py", line 156对应到你的这一行
https://github.com/thu-spmi/CAT/blob/15ed6f22b31f76f77c1349d32b824b92b1667629/src/ctc_crf/ctc_crf/__init__.py#L143
行数会不同是因为我加了几个print("")确认程式的运行，对逻辑没有影响
请问你知道如何解决吗？

**Comment by maxwellzh** [comment]
主要的报错的信息是
```
RuntimeError: Denominator LM model location is invalid: den_lm.txt.
```
应该是你指定的den_lm文件不存在，如果只是CTCLoss的训练，可以把
```
ctx = ctc_crf.CRFContext(den_lm, gpus=0)
```
注释掉

**Comment by FL990** [comment]
你好，由于遇到其他的问题比较紧急，所以都在试着除错，尚未训练den_lm
目前的问题，我猜是张量在的函式间呼叫时丢失了

状况是这样子的，当我输入进
`loss = CRFLoss(logits, labels, inputLenBatch, input_lengths)`之前打印label_lengths，结果如下
```
label_lengths = tensor([24, 48, 19, 33, 25, 22, 55, 47], device='cuda:0', dtype=torch.int32)
```
是int32、size=8的张量
理想状态是，此张量会输入到ctc_entrypoint.cu中，在那里做打印也该是相同结果对吧


使用gdb运行train_crf.py后报错
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007fff331d0be7 in get_workspace_size (label_lengths=label_lengths@entry=0x7ffe3f562a00, 
    input_lengths=input_lengths@entry=0x7ffe3f562800, alphabet_size=alphabet_size@entry=40, minibatch=minibatch@entry=8, options=..., 
---Type <return> to continue, or q <return> to quit---
    e_bytes=0x7fffffffbea8) at /nfs/Workspace/deep_avsr/video_only/ctc_crf/gpu_ctc/ctc_entrypoint.cu:78
78          int maxL = *std::max_element(label_lengths, label_lengths + minibatch);
```
(就是发issue时有提到的的错误)

使用gdb打印
```
(gdb) p sizeof(label_lengths)
$1 = 8
```
一个int的size为4，看起来这里的label_lengths只包含2个int的大小(应该要有8个int才对)
```
(gdb) p *label_lengths@2
$3 = {0, 0}
```
接着尝试印出8个(虽说超过大小，但给印)
```
(gdb) p *label_lengths@8
$3 = {0, 0, 0, 0, 0, 0, 0, 0}
```
值全为0，代表资料没有喂进来


然后我的batchsize(minibatch)设定为8，而一个int的size为4
正常来说label_lengths包8个int，他的size应为8x4=32
所以我推测在这行
```
int maxL = *std::max_element(label_lengths, label_lengths + minibatch);
```
存取的记忆体`(label_lengths + minibatch)`不存在，于是出现`signal SIGSEGV, Segmentation fault
`

问题有两个
(1)label_lengths的size不对
(2)而且内容全为0

且无论是`CTCLoss`或`CRFLoss`都遇上了这个问题，想请问在`core.gpu_ctc`中有什么需要注意但我没注意到的吗?
或是我还能怎么去除错?

**Comment by maxwellzh** [comment]
参考 #60 中的做法，传入的参数除了`logits`在GPU上，其他3个参数应该置于CPU

**Comment by FL990** [comment]
的确是因为张量放在GPU所以读不到，改成放CPU就没问题了! 十分感谢！
`CTCLoss`可以正常运行，接下来我会照你说的训练`den_lm.fst`并尝试使用`CRFLoss`。

**Comment by FL990** [comment]
抱歉，这几天生病了稍微耽误了实验的时间
好消息是，我照着你的步骤试着训练语言模型，用于初始化CRFLoss，也成功了
现在我在训练我的DL模型，看起来一切正常
谢谢你帮忙解惑！
