### ISSUE TITLE
安装  ctc-crf 包的问题

### ISSUE THREAD

**Issue by liubin3702** [thu-spmi/CAT#65]
按照教程按照安装没问题 中间没看到报错，显示安装成功；但 报错： **No module named 'ctc_crf._C'**

**Comment by maxwellzh** [comment]
请检查你的python程序执行位置，如果在`CAT/src/ctc_crf/`下运行（因为该目录下有`ctc_crf/__init__.py`，的确会报这个错误，可以尝试切换到其他目录执行，例如：
```bash
cd ~ && python -c "import ctc_crf"
cd - >/dev/null
```

**Comment by liubin3702** [comment]
确实就是在这个目录报错  外面就对的

**Comment by maxwellzh** [comment]
@liubin3702 
这是正常的情况，不会影响使用
