### ISSUE TITLE
CTC Beam Search for CTC-CRF 

### ISSUE THREAD

**Issue by Sundy1219** [thu-spmi/CAT#67]
我两个个问题想问下，
1 得到logits后，如果再接softmax，是不是可以得到音素的概率分布？
2 可以对得到的音素概率采用CTC greedy或CTC beam search解码吗？这样可以得到最佳的音素序列吗？还是说需要den_lm.fst参与计算才可以?（这里不需要涉及到音到字的解码)

谢谢

**Comment by maxwellzh** [comment]
1. 是的
2. 是可以的，但是这样得到的只是音素序列；
此外，CTC-CRF损失下训练的模型，由于训练时den_lm会影响encoder，解码时如果只用encoder输出做beam search，这会带来比较大的training & inference mismatch 问题，导致错误率（这里是phone error rate）偏高。
因此，如果你只需要获得音素序列，可以尝试做CTC beam search的同时，和一个phone lm做fusion，效果应该会比直接解码好很多。

**Comment by Sundy1219** [comment]
**"training & inference mismatch 问题"**
这个确实是我思考的问题，我之前是ctc loss训练的，然后用ctc greedy(beam search)解码出best path，现在看来换成ctc-crf后，直接用ctc_greedy解码是有问题的，至少是不准确的，需要配合phone语言模型使用．你说的phone lm，是指ctc_beam_search中嵌入lm吗？类似百度提出的那种吗？ctc_beam_search+lm解码？

**Comment by Sundy1219** [comment]
![2022-11-18 15-54-40屏幕截图](https://user-images.githubusercontent.com/19542945/202650140-f56a25ec-a21a-4c15-89a7-ff9cdc8597a5.png)
这是我在tensorflow上跑起来的,LER是phone error rate，超过了1.  这loss看着是正常的，也是在下降的

**Comment by maxwellzh** [comment]
> 你说的phone lm，是指ctc_beam_search中嵌入lm吗？类似百度提出的那种吗？ctc_beam_search+lm解码？

一般我们做beam search时，选取候选token的方式为 argmax(log P_am(Y|X))，增加一个语言模型后，变为argmax (log P_am(Y|X) + alpha * log P_lm(Y))，这里 alpha 是一个可调参数。

另外
1. 有关LM融合的理论，可以看看我们最近发表的文章 [An Empirical Study of Language Model Integration for Transducer based Speech Recognition](https://arxiv.org/abs/2203.16776)中Section 2，这个工作是在RNN-T上做的，但是理论对于端到端模型应该都适用；
2. 关于代码实现，因为我主要用的是PyTorch，我不太清楚TF下如何实现 ctc beam search + lm，pytorch实现可以参考
   - 我们即将发布的v3版本演示了如何从头开始完成CTC-CRF的数据准备、模型训练、解码（WFST or beam search） https://github.com/thu-spmi/CAT/tree/v3-dev/egs/TEMPLATE/exp/asr-ctc-crf
   - 开源的 [ctcdecode](https://github.com/parlance/ctcdecode#how-to-use) 项目，只支持n-gram lm

**Comment by Sundy1219** [comment]
上图中的LER是没有加语言模型的，是ctc greedy解码的．
你们的ASR数据准备，模型训练，解码，我基本上是了解的．
我现在的任务是想用你们的ctc-crf loss训练出来的模型做唤醒词识别kws．我们是基于唤醒词音素序列的score做判断的．所以这里有两个问题:
   1　你们blank label默认就是0，是吧？
   2　我们需要模型的输出logits，可以进行算score，之前用ctc时，我们是把logits送到ctc的前向计算中，算出唤醒词的前向分数score，这里面不会涉及到phone lm相关的东西. 如果用你们的ctc-crf，计算前向分数时，该咋算，或者说我在ctc loss前向分数的计算上，如何带上phone_lm的分数?

**Comment by maxwellzh** [comment]
1. 是的
2. ctc-crf + lm / ctc + lm 在inference做法上应该没有区别，根据我的理解，前向计算中ctc本身的score不变，额外引入lm后，
对每一帧t，如果输出token = blank，则不需要插入lm score；如果token != blank，则计算 log P_lm(token|...) 作为 lm score
总的score由ctc score + lm score得到
