### ISSUE TITLE
online decode?

### ISSUE THREAD

**Issue by hitxujian** [thu-spmi/CAT#8]
is it possible to do online decoding? thanks

**Comment by hitxujian** [comment]
it's my fault,i have not compile kaldi successful.

**Comment by hitxujian** [comment]
ERROR (latgen-faster[5.5]:ToInt():parse-options.cc:591) Invalid integer option ""

**Comment by thu-spmi** [comment]
The low-latency CAT models, as shown in Table 4 in [https://arxiv.org/pdf/1911.08747.pdf](the CAT paper) can be used for online decoding.
But you need an online decoder.
