### ISSUE TITLE
关于ctc反向传播求导公式的实现问题 

### ISSUE THREAD

**Issue by l2009312042** [thu-spmi/CAT#81]
在gpu_ctc_kernels.h 这个文件中，计算的关于softmax的梯度，代码如下
```
// grad for softmax
for (int idx = tid, j = 0; idx < uniquelabels; idx += blockDim.x, ++j) {
     const int grads_offset = prob_offset + start_prob_col + keys_shared[idx];
     // output[idx] = accum[j];
     grads[grads_offset] = exp(accum[j] - probs[grads_offset] - log_partition);
}
````
不同的beta初值，其梯度是有差异的，下图是反向传播的推导公式，
左边来自[博客](https://blog.csdn.net/Robbery07/article/details/119639033)
右边来自[原始论文](http://www.cs.toronto.edu/~graves/icml_2006.pdf)
我们这边使用的右边的初值方式，感觉应该是
 grads[grads_offset] = exp(accum[j] - 2*probs[grads_offset] - log_partition);
这里的实现是否有问题，还请帮确认一下？

![image](https://github.com/thu-spmi/CAT/assets/5296159/5c1ddd4e-5a96-4b07-9bad-019430c797e9)

**Comment by maxwellzh** [comment]
你好，我想这个问题和 beta 的初始化定义无关。左边来自博客的公式我不确定是否正确，仅从右边论文原文公式分析。

公式 (15) 中 y_k^t 表示的是softmax输出的概率，而代码中计算的是对 log-softmax 输出的梯度，又因为有
<img width="123" alt="截屏2023-07-04 21 28 00" src="https://github.com/thu-spmi/CAT/assets/32546978/8b43b0b8-b7f1-4b72-bf89-7e16943e8685">
可知公式 (15) 与当前代码是一致的。

**Comment by l2009312042** [comment]
是的  是关于logsoftmax求导的  公式是对y  有这个差异  ，问题关闭 ，感谢。
